- docs/Common.tex
Update program, team, and member info in `common.tex`.
> Update program, team, and member info

- docs/ProblemStatementAndGoals/ProblemStatement.tex
> Add problem and stakeholders

- docs/ProblemStatementAndGoals/ProblemStatement.tex
Update problem subsection in the problem statement
> Update Problem Statement Problem Subsection

- docs/ProblemStatementAndGoals/ProblemStatement.tex
https://github.com/arkinmodi/project-sayyara/issues/13
> Add stretch goals and update stakeholders

- docs/DevelopmentPlan/DevelopmentPlan.tex
> Create workflow plan

- docs/ProblemStatementAndGoals/ProblemStatement.tex
Add list of inputs and outputs for problem statement
> List of inputs and outputs for problem statement

- docs/ProblemStatementAndGoals/ProblemStatement.tex
Add hardware and software environments to problem statement
> Add hardware and software environments

- docs/DevelopmentPlan/DevelopmentPlan.tex
> Add proof of concept demo plan

- docs/DevelopmentPlan/DevelopmentPlan.tex
Relate https://github.com/arkinmodi/project-sayyara/issues/20
> Add GitHub Milestones to the workflow plan

- docs/ProblemStatementAndGoals/ProblemStatement.tex
#11 
[Problem Statement] Update inputs, outputs, goals
> [Problem Statement] Update inputs, outputs, goals

- docs/DevelopmentPlan/DevelopmentPlan.tex
> Polish Development Plan

- docs/ProblemStatementAndGoals/ProblemStatement.tex
#11
[Problem Statement] Fix typos and polish
> [Problem Statement] Fix typos and polish

- .github/workflows/build-docs.yml
Close https://github.com/arkinmodi/project-sayyara/issues/39
**Todo**
- It is not faster
> PDF Pipeline updates for branch protection

- .vscode/settings.json
- ignore-build-step.sh
- package.json
Close https://github.com/arkinmodi/project-sayyara/issues/78
> Create build ignore script

- docs/SRS/SRS.tex
> [SRS] Add purpose of project

- docs/SRS/SRS.tex
Close https://github.com/arkinmodi/project-sayyara/issues/61
> Add stakeholders

- docs/SRS/SRS.tex
[SRS] Add FR for authentication
- FRs for sign up
- FRs for login
> [SRS] Add FR for authentication

- docs/Common.tex
- docs/SRS/SRS.tex
[Common][SRS] Fix program name, add SRS subtitle
> [Common][SRS] Fix program name, add SRS subtitle

- docs/SRS/SRS.tex
Relate  https://github.com/arkinmodi/project-sayyara/issues/92
> [SRS] Add Reflections Starter

- docs/SRS/SRS.tex
> [SRS] Add Shop Lookup FRs

- docs/HazardAnalysis/HazardAnalysis.tex
Pull in updates from https://github.com/smiths/capTemplate/commit/429961dc3734eac815562bc584039a788d23ec46
> Hazard Analysis Template Updates

- .vscode/settings.json
- docs/HazardAnalysis/HazardAnalysis.tex
Relate https://github.com/arkinmodi/project-sayyara/issues/132
> [Hazard Analysis] Create FMEA Table

- package-lock.json
- package.json
- src/pages/_app.tsx
- src/redux/reducers/index.ts
- src/redux/sagas/index.ts
- src/redux/store.ts
Add plumbing for redux and sagas
Closes #123
> [Redux] Add plumbing for redux and sagas

- docs/HazardAnalysis/HazardAnalysis.tex
Relate https://github.com/arkinmodi/project-sayyara/issues/132
> [Hazard Analysis] Update FMEA table

- docs/DevelopmentPlan/DevelopmentPlan.tex
Updates from https://github.com/smiths/capTemplate/commit/9f3afce1019d9b2839f5b54b3f04d98b46553074
> Base Template Updates

- docs/HazardAnalysis/HazardAnalysis.tex
Relate https://github.com/arkinmodi/project-sayyara/issues/97
> Add missing sections

- docs/SRS/SRS.tex
> [SRS] Update SRS with Hazard Analysis information

- .github/workflows/lint-app.yml
Close https://github.com/arkinmodi/project-sayyara/issues/171
> Add typechecking stage

- docs/VnVPlan/VnVPlan.tex
Close https://github.com/arkinmodi/project-sayyara/issues/158
> Add Software Validation Plan

- CONTRIBUTING.md
- package.json
Close https://github.com/arkinmodi/project-sayyara/issues/30
> Create Contribution Guide

- docs/VnVPlan/VnVPlan.tex
> [VnV Plan] Add summary

- docs/VnVPlan/VnVPlan.tex
> [VnV Plan] Add objectives

- docs/VnVPlan/VnVPlan.tex
> [VnV Plan] Fix test label formatting

- docs/VnVPlan/VnVPlan.tex
[VnV Plan] Add system tests for employee management
Close #181
> [VnV Plan] Add system tests for employee management

- docs/VnVPlan/VnVPlan.tex
> [VnV Plan] Move NFRTs to correct section

- docs/VnVPlan/VnVPlan.tex
Relate https://github.com/arkinmodi/project-sayyara/issues/194
> [VnV Plan] Add reflection template

- docs/VnVPlan/VnVPlan.tex
Relate https://github.com/arkinmodi/project-sayyara/issues/194
> [VnV Plan] Add reflection

- docs/VnVPlan/VnVPlan.tex
> [VnV Plan] Fix spelling

- docs/VnVPlan/VnVPlan.tex
> [VnV Plan] Add reason for so many manual tests

- docs/VnVPlan/VnVPlan.tex
> [VnV Plan] Remove comment

- docs/SRS/SRS.tex
Close https://github.com/arkinmodi/project-sayyara/issues/258
> [SRS] Add List of Tables and Figures

- package-lock.json
- package.json
- src/pages/_app.tsx
- src/pages/api/user/register.ts
- src/pages/auth/login.tsx
- src/pages/auth/register.tsx
- src/redux/actions/IActionWithPayload.ts
- src/redux/actions/authActions.ts
- src/redux/reducers/authReducer.ts
- src/redux/reducers/rootReducer.ts
- src/redux/sagas/authSaga.ts
- src/redux/sagas/rootSaga.ts
- src/redux/selectors/authSelectors.ts
- src/redux/state/user/authState.ts
- src/redux/store.ts
- src/redux/types/authTypes.ts
- src/styles/pages/auth/Auth.module.css
[PoC][Auth] Update auth form and add redux
> [PoC][Auth] Update auth form and add redux

- src/pages/auth/register.tsx
- src/redux/actions/authActions.ts
- src/redux/sagas/authSaga.ts
[PoC][Auth] Automatically login after successful registration
> [PoC][Auth] Automatically login after successful registration
